# Generated by Django 5.0.1 on 2024-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.skill'),
        ),
    ]
