# Generated by Django 5.0.1 on 2024-02-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Умение', 'verbose_name_plural': 'Умения'},
        ),
    ]
